### ISSUE TITLE
[SUGGESTION] Make v3 iso and program

### ISSUE THREAD

**Issue by GitHubUser-2492** [MishaTY/Rectify11Installer#10]
👀👀👀👀

**Comment by rounk-ctrl** [comment]
Ok

**Comment by Vichingo455** [comment]
That's what I asked too

**Comment by XPnerdYT** [comment]
We are very sorry but we will not be making a ISO (or at least our team will not and there may be unofficial ISOs). As Microsoft considers it as illegal (Just- we're not supposed to do it and we can get sued) and as we don't want to be sued, we will not make an ISO. On the other hand, modifying Windows files is allowed so we made an installer. Thank you for your feedback!

**Comment by GitHubUser-2492** [comment]
what about v2

**Comment by XPnerdYT** [comment]
We made an iso for v2 because we didn't know about that until people told us, and it wasn't that big of a thing back then so we were pretty lucky but as i said we don't want to take the risk we will not make one.

**Comment by rounk-ctrl** [comment]
there will be an option to rectify a windows 11 iso
