### ISSUE TITLE
What happens with sfc and DISM scans? will they receive errors after installing rectify11?

### ISSUE THREAD

**Issue by bigplayer-ai** [MishaTY/Rectify11Installer#100]
### Description

What happens with sfc and DISM scans? will they receive errors after installing rectify11?

### Steps To Reproduce

What happens with sfc and DISM scans? will they receive errors after installing rectify11?

### Rectify11 Version

4.0

### Windows Version

11 22h2 22521

### Logs

What happens with sfc and DISM scans? will they receive errors after installing rectify11?

**Comment by HolyNetworkAdapter** [comment]
not a bug, also i dont know

**Comment by Typical0** [comment]
sfc /scannow will restore old Windows 11 files, DISM works properly.
