### ISSUE TITLE
Broken scroll bars in light mode!

### ISSUE THREAD

**Issue by Terry69696969** [MishaTY/Rectify11Installer#101]
### Description

![Capture](https://user-images.githubusercontent.com/123395629/214600712-5a59a5c9-08be-40c3-9aaf-edebd85e196c.PNG)

### Steps To Reproduce

no

### Rectify11 Version

3.0 rp3

### Windows Version

Windows 11 22H2

### Logs

no

**Comment by ilovepcs** [comment]
Looks like you have StartAllBack installed. It does this bug when Rectify11 is installed.

**Comment by Terry69696969** [comment]
> 

is there anyway i can use startallback and have the r11 theme too? maybe using an older version of start all back

**Comment by ilovepcs** [comment]
Well you need to do this:

1. Rename C:\Windows\Resources\Themes\Rectified\Aero.msstyles to another name.
2. Open C:\Windows\Resources\Themes\lightrectified.theme in Notepad.
3. You should find "Aero.msstyles", change it to the renamed msstyles file.
4. Win+R, themetool.exe, apply the dark theme then the light theme again.

**Comment by Terry69696969** [comment]
> 

ill try ty

**Comment by Terry69696969** [comment]
> 4\. pply the dark theme then the light theme again

it actually worked tysm
