### ISSUE TITLE
DPI issues are back

### ISSUE THREAD

**Issue by A-Loot** [MishaTY/Rectify11Installer#103]
### Description

In the latest installer version from GitHub Actions (commit c0df75fe040310bd0a8a2398f74d4e7dc585a39c) the Installer isn't rendered properly when you enable scaling in Windows (for example most Laptops have 125% scaling activated by deafult).

This problem has been fixed previously but was reintroduced in commit 1d2a74d4d6215fbe27b045a5d0b33e4473dd8289

### Steps To Reproduce

just open the installer with Windows scaling active

### Rectify11 Version

latest exe from GitHub Actions (commit c0df75fe040310bd0a8a2398f74d4e7dc585a39c)

### Windows Version

Windows 11 22H2

### Logs

Installer before commit 1d2a74d4d6215fbe27b045a5d0b33e4473dd8289 with 125% scaling:
![R11 before](https://user-images.githubusercontent.com/105282948/217751697-d2f26628-2b0f-492f-bd65-da2dfcacfb2f.png)

Installer using the current commit c0df75fe040310bd0a8a2398f74d4e7dc585a39c with 125% scaling:
![R11 now](https://user-images.githubusercontent.com/105282948/217752126-fe126964-f19d-49e5-b0d0-314a4ea7dae4.png)

**Comment by rounk-ctrl** [comment]
It worked before? i thought the contents got cut off

**Comment by rounk-ctrl** [comment]
Try latest commit
