### ISSUE TITLE
Barely visible "Patching" text on light mode

### ISSUE THREAD

**Issue by s1stine** [MishaTY/Rectify11Installer#104]
### Description

The title says it all, only fixed if you use dark mode

### Steps To Reproduce

Use Windows light mode and run the installer

### Rectify11 Version

Latest commit

### Windows Version

Windows 11 22H2 22621.525

### Logs

![Screenshot 2023-02-09 194740](https://user-images.githubusercontent.com/82517584/217818277-4d98f484-4854-442d-a39d-3b01e578e54d.png)

**Comment by rounk-ctrl** [comment]
fixed
