### ISSUE TITLE
Old releases have disappeared

### ISSUE THREAD

**Issue by aaronliu0130** [MishaTY/Rectify11Installer#105]
### Description

The only two tags that remain right now are 3.0rp3 and 3.0rp2. All the rest have disappeared. Additionally, the website is down.

### Steps To Reproduce

Go to https://github.com/MishaTY/Rectify11Installer/tags

### Rectify11 Version

Irrelevant

### Windows Version

Irrelevant

### Logs

![image](https://user-images.githubusercontent.com/11874211/218283275-477335af-51ad-4a35-8a09-feabdcccaf90.png)
![image](https://user-images.githubusercontent.com/11874211/218283336-fc0b03bf-f4a0-435f-9e28-1ed3b59bb11f.png)

**Comment by MishaTY** [comment]
@ojask why

**Comment by Typical0** [comment]
Rectify11 installers prior to RP2 were archived, because they were unstable. All releases till v3 RP can be found here: https://archive.org/details/r11installerarchive

**Comment by fytuf** [comment]
> @ojask why

doubt ojas did this

**Comment by aaronliu0130** [comment]
Ah, thanks. Is there any plan for the website?

**Comment by fytuf** [comment]
it'll come back up when v3 finally launches

**Comment by Typical0** [comment]
Website for now has no specified ETA.
