### ISSUE TITLE
miss an file

### ISSUE THREAD

**Issue by rraffaelandrei** [MishaTY/Rectify11Installer#107]
### Description

Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'D:\Download\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Resources\Rectify11ControlCenter.exe'. Line 3018, position 5.	Rectify11Installer	D:\Download\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Properties\Resources.resx	3018	

### Steps To Reproduce

Severity	Code	Description	Project	File	Line	Suppression State
Error		Invalid Resx file. Could not find file 'D:\Download\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Resources\Rectify11ControlCenter.exe'. Line 3018, position 5.	Rectify11Installer	D:\Download\Rectify11Installer-master\Rectify11Installer-master\Rectify11Installer\Properties\Resources.resx	3018	

### Rectify11 Version

3.0 rp3

### Windows Version

windows 10 21h2

### Logs

![Screenshot 2023-02-12 074151](https://user-images.githubusercontent.com/91460382/218321091-62abde61-e6b2-4dbe-9dbc-823f41656e34.png)

**Comment by rraffaelandrei** [comment]
some can give that file?

**Comment by MishaTY** [comment]
Hi, you need to compile the Rectify11ControlCenter submodule.

**Comment by rraffaelandrei** [comment]
ok thank you
