### ISSUE TITLE
Rectify11 Installer freezes while patching files

### ISSUE THREAD

**Issue by ImSwordKing** [MishaTY/Rectify11Installer#110]
### Description

Rectify11 v3.0.24.0 stops responding while patching files. It still continues to patch files in the background and opens the CMD prompt to copy the files over but after everything is done it does not change the theme and restart.

### Steps To Reproduce

1. Install Rectify11 with all icons, themes and accent colorizer enabled.
2. Wait until shell32 is getting patched
3. The program should stop responding which is fine for a small period of time. but instead it gets stuck for a longer period of time and prevents the program from restarting the device.

### Rectify11 Version

v3.0.24.0

### Windows Version

Windows 11 21H2 22000.1574

### Logs

═════════════════════════════
START: 2/18/2023 6:10:11 AM
Rectify11 Version: 3.0.24.0
═════════════════════════════

**Comment by ImSwordKing** [comment]
I'm using [fix thread access violation](https://github.com/MishaTY/Rectify11Installer/actions/runs/4156639065) Rectify11 #139: Commit [af00a74](https://github.com/MishaTY/Rectify11Installer/commit/af00a7458ade682f31c5b1df46644dabacc021b3) pushed by [MishaTY](https://github.com/MishaTY)

**Comment by rounk-ctrl** [comment]
does 05d9ac6 work?

**Comment by rounk-ctrl** [comment]
Should be fixed in latest commit
