### ISSUE TITLE
Discussion: The Discord just completely imploded

### ISSUE THREAD

**Issue by daemonspudguy** [MishaTY/Rectify11Installer#111]
I don't even know what just happened. The Discord got a sudden burst of spam, and now is gone.

**Comment by KingGamingYT** [comment]
rip

**Comment by BlueMoon1890** [comment]
Bump.

I'm wondering what happened, I've followed development for a while and it looked like everything was going ok. 

Is the project dead?

**Comment by Cartrigger** [comment]
i have no idea what happened either

**Comment by infiniwave** [comment]
I witnessed it. There was at least one rogue moderator and at least 12 pings to everyone, and the server went completely insane

The project is not dead. Not sure what occurred afterwards leading to its destruction

**Comment by Zoomer1234** [comment]
Rectify Modding Hub remains untouched, and is still read only, while the main Rectify11 server is gone

**Comment by daemonspudguy** [comment]
Appears to have been deleted, as every single link I can find says it's expired.

**Comment by Zoomer1234** [comment]
Perhaps the rectify modding hub could be used as a replacement, but the modding team definitely needs a rework.

**Comment by infiniwave** [comment]
That is likely, but removing channels also deletes their associated invites, so there could be a chance that it isn't

**Comment by daemonspudguy** [comment]
The server also disappeared from my sidebar, so if it wasn't deleted than I was banned at random.

**Comment by infiniwave** [comment]
I did see channels being deleted prior to me being removed from the server

**Comment by Zoomer1234** [comment]
nah, everybody seemingly got kicked so its dead.

**Comment by Cartrigger** [comment]
there was atleast 2 or 3 rouge mods

hopefully there will be a new server

**Comment by daemonspudguy** [comment]
Rogue mods, you mean? Rouge is French for red.

**Comment by KingGamingYT** [comment]
whats the link to the modding hub?

**Comment by Zoomer1234** [comment]
server was too big for the modding system/team it would seem

**Comment by RheaTF2** [comment]
I think it would be better for everyone if we just stopped talking about it. iirc we moved to the everything windows server for now.

**Comment by infiniwave** [comment]
They literally just recently reworked their staff team, though

**Comment by egold555** [comment]
The old Rectify Modding Hub is still up, though it is read only: 
https://discord.gg/3tppcucT

**Comment by zachariapopcorn** [comment]
well that sucks

**Comment by RedPCat** [comment]
From what I know, it got deleted because of NSFW & Pings

**Comment by As2Bax** [comment]
I just witnessed the nuke, and it was crazy.

**Comment by DeltaSaadi** [comment]
Bummer, I had been waiting for the release on discord but I hope you guys will release it via GitHub.

**Comment by itsHanibee** [comment]
from what people are saying the project itself isn't dead, only the discord side of things are.., the rectify image itself isn't completely tarnished but a rebranding might be in order

**Comment by daemonspudguy** [comment]
I just rejoined the now archived old server, hopefully it will be revived in the wake of this utter chaos. Not the best way to end a Sunday IMHO.

**Comment by EverythingWindows** [comment]
For those of you who wondering why the server got deleted is that:
1. The server is too big to maintain by the prominent member of the community.
2. The lead developer wants the "Rectify" name to be clean without all social intervention (eg. drama, child actions, etc.)

Hope this information will help you understand the situation.

**Comment by fddaa** [comment]
It will be missed.

**Comment by MishaTY** [comment]
We just unarchived Windows Mod hub. Link: https://discord.gg/Hk4kjMPV84 The new rectify11 server is made, but invite won't be posted until @ojask approves.

**Comment by MishaTY** [comment]
After further considerations, Rectify11 will not have an official discord server.

**Comment by SmirbYrneh420** [comment]
Here lies Rectify 11 Discord.
2020? - 2023
Cause of death: Rogue moderators
F in the chat everyone!

**Comment by fytuf** [comment]
> Here lies Rectify 11 Discord.
> 2020? - 2023
> Cause of death: Rogue moderators
> F in the chat everyone!

fuck you

**Comment by travy-patty** [comment]
Smoking that Rectify11 Discord pack

**Comment by fytuf** [comment]
> Smoking that Rectify11 Discord pack

ur not making us look any better dude

**Comment by fddaa** [comment]
> Here lies Rectify 11 Discord. 2020? - 2023 Cause of death: Rogue moderators F in the chat everyone!

Sir not a single mod went rogue.

**Comment by fytuf** [comment]
> > Here lies Rectify 11 Discord. 2020? - 2023 Cause of death: Rogue moderators F in the chat everyone!
> 
> Sir not a single mod went rogue.

exactly, its just misha that started spreading fucking lies about us

**Comment by MishaTY** [comment]
Where

**Comment by fytuf** [comment]
> Where

stop playing fucking dumb with me, we've been over this multiple times

**Comment by FavoritoHJS** [comment]
> Sir not a single mod went rogue.

I mean, sure... aside from the 3 that spammed the announcements channel

anyways can this get closed for contributors only?

**Comment by fytuf** [comment]
> > Sir not a single mod went rogue.
> 
> I mean, sure... aside from the 3 that spammed the announcements channel
> 
> anyways can this get closed for contributors only?

we had permission from ojas to do that though

**Comment by FavoritoHJS** [comment]
[citation needed], also why explode the discord when "this guild is abandoned and will not be used any further" works as well

**Comment by HolyNetworkAdapter** [comment]
I am a moderator in that server during the 5 minute and this is what I will say:
We did not go rogue. Ojas basically wanted the server to go into a free for all for 5 minutes before getting banned. This did not apply just to mods, but members too IIRC. People just thought we were going rogue, and this is why we're getting all the trash thrown at us. I will say this again, **we did not go rogue.** Please stop thinking that.

**Comment by FavoritoHJS** [comment]
and why the ban?

**Comment by HolyNetworkAdapter** [comment]
There was no ban, the server is gone.

**Comment by Orangera1n** [comment]
It was a server deletion

**Comment by FavoritoHJS** [comment]
...so why was the server deleted then?

**Comment by BlueMoon1890** [comment]
> I was a moderator in that server during the 5 minute and this is what I will say: We did not go rogue. Ojas basically wanted the server to go into a free for all for 5 minutes before getting banned. This did not apply just to mods, but members too IIRC. People just thought we were going rogue, and this is why we're getting all the trash thrown at us. I will say this again, **we did not go rogue.** Please stop thinking that.

That is definitely the most shitbrained way to end a server if you care about your image like you claim to be earlier in this thread

**Comment by HolyNetworkAdapter** [comment]
> > I was a moderator in that server during the 5 minute and this is what I will say: We did not go rogue. Ojas basically wanted the server to go into a free for all for 5 minutes before getting banned. This did not apply just to mods, but members too IIRC. People just thought we were going rogue, and this is why we're getting all the trash thrown at us. I will say this again, **we did not go rogue.** Please stop thinking that.
> 
> That is definitely the most shitbrained way to end a server if you care about your image like you claim to be earlier in this thread

I did not decide to delete the server if thats what you mean

**Comment by HolyNetworkAdapter** [comment]
IIRC it got deleted because of how immature the community was. The everyone ping incident only made it worse. I'm not Ojas, so you should probably talk to him if you want all the details.

**Comment by BlueMoon1890** [comment]
> > > I was a moderator in that server during the 5 minute and this is what I will say: We did not go rogue. Ojas basically wanted the server to go into a free for all for 5 minutes before getting banned. This did not apply just to mods, but members too IIRC. People just thought we were going rogue, and this is why we're getting all the trash thrown at us. I will say this again, **we did not go rogue.** Please stop thinking that.
> > 
> > 
> > That is definitely the most shitbrained way to end a server if you care about your image like you claim to be earlier in this thread
> 
> I did not decide to delete the server if thats what you mean

Not you specifically but for the entire R11 team it's definitely not a good look at all

**Comment by FavoritoHJS** [comment]
> I did not decide to delete the server if thats what you mean
i mean, sure, but why did it have to end in it becoming the newest anarchy server on discord instead of, you know, using the announcement made minutes prior to say "also this discord is no longer official"

**Comment by HolyNetworkAdapter** [comment]
I wasn't part of the R11 team. I submitted a commit once but it was denied (it was checking the OS for build string 21996 or later)

**Comment by HolyNetworkAdapter** [comment]
> > I did not decide to delete the server if thats what you mean
> 
> i mean, sure, but why did it have to end in it becoming the newest anarchy server on discord instead of, you know, using the announcement made minutes prior to say "also this discord is no longer official"

Ojas decided this is how he wanted it to end.

**Comment by FavoritoHJS** [comment]
welp, guess this is another project run by a clueless leader, welcome to the vaporwave club i guess

**Comment by BlueMoon1890** [comment]
"the community is too immature, we gotta end the server"

*Ends the server in the most immature way possible that makes your brand image look horrible*

**Comment by HolyNetworkAdapter** [comment]
Basically, **the new mods were not at fault.** Even if the staff refactor never happened, the everyone ping incident would've happened.

**Comment by travy-patty** [comment]
immature community immature ending lol

**Comment by HolyNetworkAdapter** [comment]
I'm not against Ojas here so I don't really have a stance on his actions.

**Comment by FavoritoHJS** [comment]
> Basically, the new mods were not at fault. Even if the staff refactor never happened, the everyone ping incident would've happened, and the server would have the exact same end.

except without the "anarchy" phase that would tarnish everything even worse... hopefully

**Comment by HolyNetworkAdapter** [comment]
> > Basically, the new mods were not at fault. Even if the staff refactor never happened, the everyone ping incident would've happened, and the server would have the exact same end.
> 
> except without the "anarchy" phase that would tarnish everything even worse... hopefully

The non-staff members were doing the exact same stuff as us, without the staff actions of course, so it would still kind of have the same ending.

**Comment by FavoritoHJS** [comment]
i mean, i don't remember exatly who ojas is but if he's a big deal i fear a fork will be required now since he can't be trusted to at least bring the lifeboats to the titanic

**Comment by HolyNetworkAdapter** [comment]
> i mean, i don't remember exatly who ojas is but if he's a big deal i fear a fork will be required now since he can't be trusted to at least bring the lifeboats to the titanic

Only time will tell...

**Comment by XPnerdYT** [comment]
This has literally turned into the "Discord"

**Comment by Lixkote** [comment]
e

**Comment by XPnerdYT** [comment]
Now whos gonna create the next discord

**Comment by XPnerdYT** [comment]
Because it seems that nobody plans to do so

**Comment by Orangera1n** [comment]
Sadly I don't think there will be another official one

**Comment by XPnerdYT** [comment]
I mean like anyone can make one rn

**Comment by XPnerdYT** [comment]
I can if you guys are ok

**Comment by travy-patty** [comment]
PLUG 🗣️

**Comment by XPnerdYT** [comment]
> PLUG 🗣️

Wdym

**Comment by MishaTY** [comment]
We have made a new discord server: https://discord.gg/gsgu9GCtsk

**Comment by Daph357** [comment]
smoking that pack
