### ISSUE TITLE
Installers with black topics

### ISSUE THREAD

**Issue by mateusfn98** [MishaTY/Rectify11Installer#112]
### Description

Some installers is with invisible fonts color. (same color of background)

### Steps To Reproduce

TeraCopy's installer.

### Rectify11 Version

Version: 3.0 rp3

### Windows Version

Windows 11 Pro 22H2 22621.1265

### Logs

![image](https://user-images.githubusercontent.com/74764525/220193085-d3dff971-6c1e-4c86-8249-02fc92cb63c1.png)

**Comment by fytuf** [comment]
This is sadly only fixable by the developers of these apps.

**Comment by MishaTY** [comment]
Please contact the developer of the app
