### ISSUE TITLE
Rectify11 Theme is undeletable, leading to annoying duplicates if installed multiple times

### ISSUE THREAD

**Issue by gallium-gonzollium** [MishaTY/Rectify11Installer#113]
### Description

I ran the installer multiple times and installed the themes multiple times, as I wanted to change the start menu and taskbar, etc. Upon opening the themes window, there are multiple duplicates of the Rectify11 theme that are not removable. (image below)

### Steps To Reproduce

Install the Rectify11 theme multiple times and go to the themes option in Settings.

### Rectify11 Version

Version 3.0 rp3

### Windows Version

Windows 11 22H2 22621

### Logs

![image](https://user-images.githubusercontent.com/97408555/221383568-d0e0ee61-ba74-4886-9a9f-d4af8f49bfe9.png)

**Comment by ItsProfessional** [comment]
These are not duplicates. Rectify11 installs 4 themes:
* Black
* Dark Colorized
* Dark Rectified
* Light rectified

These themes also cannot duplicate when installing rectify11 multiple times. The installer adds the rectify11 themes into the `C:\Windows\Resources\Themes\` folder, and if r11 is installed multiple times then the installer will just overrite the old copies of the installed themes.
