### ISSUE TITLE
Rectify11 Installer crashing at "Installing Runtimes"

### ISSUE THREAD

**Issue by RheaTF2** [MishaTy/Rectify11Installer#117]
### Description

On the latest version of the rectify11 installer, it crashes every time it reaches "Installing Runtimes". 

![image](https://user-images.githubusercontent.com/123844440/224552804-bde34369-5706-42d7-adbf-08328d6a5b40.png)

I tried to get the log to see what the problem was, but when I went to the file, there was nothing. It crashed before it could even log anything past the start date and time.

![image](https://user-images.githubusercontent.com/123844440/224552913-e438529c-1d77-4b6d-a8b3-a21cb2816b52.png)

I have the latest versions of the .NET 7, .NET 3.1, and Visual C++ 2015-2022 redistributables installed, so I'm not sure what the issue could be.

![image](https://user-images.githubusercontent.com/123844440/224553010-da19190d-a74b-4b42-b9a0-5371d8a0d88c.png)

### Steps To Reproduce

1) Download the latest Rectify11 installer from Github Actions
2) Go through the installer and select at least "Icons". Unsure if any other patch will trigger the need to install runtimes, but patching icons does.
3) Advance by starting the installation, and you'll be greeted by the error message.

### Rectify11 Version

Version 3.0.24.0, #157, commit 2a8530d

### Windows Version

Windows 11 Dev 23403

### Logs

![image](https://user-images.githubusercontent.com/123844440/224552913-e438529c-1d77-4b6d-a8b3-a21cb2816b52.png)

**Comment by Thisisauser6443** [comment]
Okay, so I did a bit of testing, and it seems like you only need to uninstall 2 runtimes to get past the issue:
`Microsoft Core . NET Runtime - 3.1.27`
`Microsoft Visual C++ 2015-2022 Redistributable (x64)`

**Comment by Thisisauser6443** [comment]
@A-Loot, just to confirm, .NET also throws an error with no logs if it's pre-installed, on my end

**Comment by RaphMar2021** [comment]
The exception is thrown because extras (who contains runtimes) are not packed correctly.

**Comment by scarlettekk** [comment]
https://github.com/MishaTy/Rectify11Installer/commit/d21182215f2326508bdef15c19454d906c6b7351 fixes this for me. @RheaTF2 , do you still have the issue with the latest build?

**Comment by ojask** [comment]
Issues has been fixed. Extras were packed incorrectly in previous commits.
