### ISSUE TITLE
Unable to compile

### ISSUE THREAD

**Issue by DVT7125** [MishaTY/Rectify11Installer#118]
Hi there,

I am most likly doing something wrong but when trying to compile the latest branch I get this error in VS2022

D:\Rectify11Installer-master\Rectify11Installer\Properties\Resources.resx(3018,5): error MSB3103: Invalid Resx file. Could not find file 'D:\Rectify11Installer-master\Rectify11Installer\Resources\Rectify11ControlCenter.exe'. Line 3018, position 5.

**Comment by xverge** [comment]
Did you clone submodules?

**Comment by DVT7125** [comment]
> Did you clone submodules?

How do I do that?

**Comment by xverge** [comment]
Try running `git submodule update --init` in the folder and try compiling again

**Comment by DVT7125** [comment]
> Try running `git submodule update --init` in the folder and try compiling again

Ran the command but now I get fatal: not a git repository (or any of the parent directories): .git

I think I have to tell it to find the folder of GitHub not git.....

**Comment by xverge** [comment]
Did you download it as source code?

**Comment by DVT7125** [comment]
> 

I mean I just downloaded as a zip and tried the clone through github desktop so yes?

**Comment by xverge** [comment]
Run the command in the folder you cloned with GitHub Desktop and try compiling again in that folder

**Comment by DVT7125** [comment]
> Run the command in the folder you cloned with GitHub Desktop and try compiling again in that folder

I got git to work, but when I tryied to compile same thing.


Invalid Resx file. Could not find file 'D:\Rectify11Installer\Rectify11Installer\Resources\Rectify11ControlCenter.exe'. Line 3018, position 5.	Rectify11Installer	D:\Rectify11Installer\Rectify11Installer\Properties\Resources.resx	3018

**Comment by DVT7125** [comment]
> Compile the Rectify11ControlCenter Submodule and copy the exe file from "Rectify11ControlCenter\bin" to the "Rectify11Installer\Resources" directory.

I just tried that (Sorry I was away and got sick) but that's the problem I can't compile the Rectify11ControlCenter so there is nothing to put in the "Rectify11Installer\Resources" directory.
