### ISSUE TITLE
Completely bricked my insider preview 22h2 install

### ISSUE THREAD

**Issue by Ciancy28** [MishaTY/Rectify11Installer#12]
Bootloop during system start right before lockscreen, system restore point wouldn't fix it, spent the whole day trying to fix it without luck, so far clean install seems to be the only solution.

**Comment by MishaTY** [comment]
You can just reset the setup mode registry via the command prompt in winre.

**Comment by MishaTY** [comment]
First mount the system hive from your install in /windows/system32/config/system. Then set cmdline to blank, systemsetupinproggress to 0, setuptype to 0, and setupphase to 0, in hkey_local_machine/software/hive/setup.

**Comment by Ciancy28** [comment]
> First mount the system hive from your install in /windows/system32/config/system. Then set cmdline to blank, systemsetupinproggress to 0, setuptype to 0, and setupphase to 0, in hkey_local_machine/software/hive/setup.

And how would I achieve this?
What commands do i need to put in cmd? It's the only thing that still works when booting from usb

**Comment by Ciancy28** [comment]
> First mount the system hive from your install in /windows/system32/config/system. Then set cmdline to blank, systemsetupinproggress to 0, setuptype to 0, and setupphase to 0, in hkey_local_machine/software/hive/setup.

Ok so I figured it out, and btw it wasn't hkey_local_machine/software/hive/setup but hkey_local_machine/hive/setup.
I also think I found why this happened, so I had the installer on a ramdisk instead of a regular drive, and cmdline was pointing to the ramdisk, which of course gets wiped after a reboot.
