### ISSUE TITLE
Problem with Mica in the File Explorer (Rectify11 Dark Mica theme)

### ISSUE THREAD

**Issue by VitalSkib** [MishaTy/Rectify11Installer#123]
Hey.
I have some weird visual problem with Mica in File Explorer (Extend Frame Into Client Area?) in the "Rectify11 Dark Mica" theme. 
When I open File Explorer using the "main" button on Taskbar, everything looks great. 
However, if I open it differently (for example: right click -> "Open file location" or from another program), then the background looks broken (wrong). 
And if I switch back and forth any parameter in Mica Global or Explorer rule settings then it again becomes correct.
Well, it’s hard to explain it for me, better watch the attached short video, it will become clear what I'm talking about.
So, is this some known bug/limitation, or am I doing something wrong?
Any way to fix it?

Windows 11 Pro 22H2 build 22621.1413 
(Freshly installed, without any changes and modifications)

Rectify11 Installer 
(The latest as of for now from "Actions", but I tried different installers and different options and settings variations)

tia

https://user-images.githubusercontent.com/43848892/228247065-fb0b8417-3210-4000-bf84-2aa90226716b.mp4

**Comment by SmirbYrneh420** [comment]
Must be something with ExplorerFrame. Can you check for a gift-box-like icon in the systray?

**Comment by VitalSkib** [comment]
> Must be something with ExplorerFrame. Can you check for a gift-box-like icon in the systray?

Yes, it is present and works, but for some reason, it does not work always. 
Now, I don't have enough technical knowledge and I don’t know how it is implemented, but it looks like it triggers wrong, or rather it does not triggers at all when it should.

**Comment by SmirbYrneh420** [comment]
ExplorerFrame (the thing that hooks Explorer for mica to work there) is relatively unstable…
https://github.com/micaforeveryone/explorerframe

**Comment by VitalSkib** [comment]
Oh.., I just noticed that it does the same thing in the "Dark Rectified" theme too, just without "Extend Frame Into Client Aria".
I mean, if I launch File Explorer differently, without using Taskbar button, then titlebar at first uses the Tabbed backdrop instead of a Mica.
And, as before, if I switch the rules settings in the MFE, then it becomes correct..
In this case, the ExplorerFrame is not involved, in fact it is not even launched, which says that the ExplorerFrame has nothing to do with the problem..
This makes me think that this problem lies in the "Mica For Everyone" itself. 
Any thoughts?

**Comment by VitalSkib** [comment]
> 

Yes, I tried it too, unsuccessfully, unfortunately..

**Comment by VitalSkib** [comment]
> So this problem persists even after deactivating "Extend Frame Into Client Aria" (ExplorerFrame) and updating to v1.3? If yes, then you should defenitely open an Issue on the [MicaForEveryone GitHub repository](https://github.com/MicaForEveryone/MicaForEveryone)

Yes, that's a good idea. 
I will try to ask my question on their repo too..

**Comment by VitalSkib** [comment]
> A bit late to ask, but have you activated the normal Windows11 Mica/Blur effect?

Oh of course. 
I'll be asking this on their repo today since I was a bit busy yesterday..

**Comment by VitalSkib** [comment]
> A bit late to ask, but have you activated the normal Windows11 Mica/Blur effect?

I checked all possible variations of the settings it seems. 
But could you clarify what you mean specifically, maybe I missed something?
tia

**Comment by VitalSkib** [comment]
> 

I will check it a little later and I'll inform you if it affects it or not..

**Comment by VitalSkib** [comment]
> I was wondering if anything changes when you activate/deactivate the "Transparency effects" setting in Setings/Personalization/Colors while still having MFE activated

So, all this time this switch was turned on, as it was by default. 
And if I turn it off, then yes, File Explorer begins to look almost identical, regardless of the launch method. 
But to be honest, I don’t see how it can help if all beauty is lost without transparency..?

(MFE and ExplorerFrame is launched, and Extend Frame Into Client Aria is on)

Using Taskbar button:

![Home](https://user-images.githubusercontent.com/43848892/228930140-f18ac25e-2b65-417d-bf9e-6851ebbd857b.png)

Using Open File Location:

![Rectify11ControlCenter](https://user-images.githubusercontent.com/43848892/228930181-7e27d928-3beb-4858-b1cc-129f0a3bb24a.png)

**Comment by VitalSkib** [comment]
> I was just interested if Explorer was also broken without transparency. I guess that confirms that it has to be either MFE or more likely ExplorerFrame.

Well, this is unlikely to be ExplorerFrame, because in my latest tests it is not even running. 
Most likely this is the MFE itself. 
I redirected my initial question to them ([#279](https://github.com/MicaForEveryone/MicaForEveryone/issues/279)), let's wait and we'll see what they think about it..
Thank you..
