### ISSUE TITLE
Can I translate it as Chinese?

### ISSUE THREAD

**Issue by PandaChen1** [MishaTy/Rectify11Installer#128]
Can I translate it as Chinese?I want to make it more convenient for Chinese fans to use it, I really like it, and there are many fans who like it on Bilibili.

**Comment by WinExperiments** [comment]
Sure, go ahead! You can also join our Discord server and get your Contributor role there.

**Comment by rounk-ctrl** [comment]
doesnt chinese translations already exist?

**Comment by rounk-ctrl** [comment]
..... isnt bilibili from PRC

**Comment by PandaChen1** [comment]
> doesnt chinese translations already exist?

Realy?I Don't know.

**Comment by XPnerdYT** [comment]
> Realy?I Don't know.

Yeah, I did them

**Comment by XPnerdYT** [comment]
And I believe it is up-to-date, I'll check later

**Comment by XPnerdYT** [comment]
![image](https://user-images.githubusercontent.com/87585714/231022953-0944186a-6cc6-4f14-8033-80a85166a405.png)
Fyi I am Chinese and Canadian

**Comment by PandaChen1** [comment]
我超是国人！
中文占的位置较大，窗口中标题和下方的文本间隔太近，建议稍微调整

**Comment by XPnerdYT** [comment]
> 我超是国人！
> 中文占的位置较大，窗口中标题和下方的文本间隔太近，建议稍微调整
好的，实在对不起过了一个月才回答，我们会尽快修好这个问题！
