### ISSUE TITLE
WoA version for Arm-based PC's(Laptops and Desktops) and Raspberry Pis(3&4)

### ISSUE THREAD

**Issue by FoxbitDreamtail** [MishaTY/Rectify11Installer#13]
with the increasing relevance of arm-based computers, there should be a way to make those systems look the part much like their beefier(albeit less efficient) brotherin. it would be foolish to say that Arm-based Computing is NOT the future.

**Comment by TheBeeBoi** [comment]
+1

**Comment by XPnerdYT** [comment]
This is incredibly hard to implement due to limitations of Windows. In the meantime, we are not planning to implement ARM support.
