### ISSUE TITLE
msstyles Question for Rectify11 Dev

### ISSUE THREAD

**Issue by WildByDesign** [MishaTy/Rectify11Installer#131]
### Description

To be clear, the question that I am asking is actually a Windows 11 bug specifically regarding win32-darkmode implementations. This is not a Rectify11 bug, nor is Rectify11 affected.

However, the Rectify11 msstyles actually FIXES this Microsoft bug. Hence that is why I am asking here. I don't have a Discord account. But if somebody could ask the Rectify11 developer who created the Rectify11 msstyles please ask the dev to have a look at this question. Thank you.

![_win11-button-explorer++](https://user-images.githubusercontent.com/26308319/230729100-86ac42af-7b9d-4d0f-a228-0d907d8f9116.png)
![_win11-button-libreoffice](https://user-images.githubusercontent.com/26308319/230729101-5e0e45d1-62b9-487d-95fe-e7031e9b48fe.png)
![_win11-button-notepad++](https://user-images.githubusercontent.com/26308319/230729103-99c82afe-b32d-4ff9-9ed7-2324252df026.png)

- Which element/section of an msstyles file is responsible for the highlight color of a toolbar button that is selected/active or hovered over?

This is a Microsoft bug that only seems to affect win32-darkmode implementations on Windows 11 (Windows 10 is fine). Some of the apps that use this implementation are Notepad++, Explorer++ and LibreOffice. I'm pretty sure that System Informer (previously Process Hacker) also uses win32-darkmode but does not seem to be affected.

Anyway, switching to Rectify11 msstyles fixes this bug instantly. So that is why I really would like to know which part of a msstyles file is responsible for this so that I can look into fixing it in other msstyles.

### Steps To Reproduce

N/A

### Rectify11 Version

latest

### Windows Version

Windows 11 22H2

### Logs

n/a

**Comment by WinExperiments** [comment]
Hello, I am the one who developed the Rectify11 msstyles, and these look like the Toolbar class, parts being Button for Explorer++ and Notepad++, and SplitButton and SplitButtonDropdown for LibreOffice. However the dropdown glyph (arrow) used by LibreOffice isn't msstyles based; it uses a custom drawn one.

**Comment by WinExperiments** [comment]
Can you also show how it looks with Rectify11 msstyles?

**Comment by WildByDesign** [comment]
Thanks, @WinExperiments I appreciate it. I'm trying to figure out some potential fixes for those programs. The problem is in Microsoft's own msstlyes though but I am brainstorming some ideas. I will close this issue now since you have answered my question. Thanks again.

Here are the screenshots of those programs win32-darkmode implementations and using Rectify11:

![_win11-button-explorer++2](https://user-images.githubusercontent.com/26308319/230746873-6cfc26cb-2c4a-453e-a00a-6c477428b2cf.png)
![_win11-button-libreoffice2](https://user-images.githubusercontent.com/26308319/230746875-9c4cad22-8745-434b-ab63-84727c531773.png)
![_win11-button-notepad++2](https://user-images.githubusercontent.com/26308319/230746876-7a516d63-b5c1-415f-8672-7841015ba8b2.png)

Everything looks so much better with your Rectify msstyle themes. The Notepad++ icons look a bit funny because the developer had to invert the icon color to deal with the issue temporarily. None of the devs have been able to find a solution to this yet though.
