### ISSUE TITLE
Causes Radeon Pro Software to crash

### ISSUE THREAD

**Issue by ghost** [MishaTY/Rectify11Installer#19]
After installing Rectify11, the Radeon Pro Software crashes when started, displaying the following error message:

---

"The instruction at 0x00007FF69169FC98 referenced memory at 0x0000000000000000. The memory could not be read.

Click on OK to  terminate the program"

---

I've attached a screenshot of the error:
![image](https://user-images.githubusercontent.com/84929191/184766714-408c86ad-0c5d-4aac-90cf-7cf88b232e07.png)

**Comment by XPnerdYT** [comment]
I don't think this is rectify11s problem, idk why but theres literally no fix online. You might as well try reinstalling Radeon Pro.
