### ISSUE TITLE
please unban me from discord

### ISSUE THREAD

**Issue by KingTino104** [MishaTY/Rectify11Installer#2]
yeah... im here now

**Comment by KingTino104** [comment]
yes, inkatail#2164
i dont even know why im doing it here. b
buttt since there are no real issues here, i decided why not

**Comment by inkatail** [comment]
if u will ask on every website just to unban you
then you will get not unbanned lmao

**Comment by Typical0** [comment]
you shouldn't join on a alt

**Comment by KingTino104** [comment]
just unban me

**Comment by iamshivayep** [comment]
Bro you literally say youre "not underage" while you do this nonsense that only a 10 year old can do, i didnt do this nonsense back when i was banned from R11 as a joke, i just said to ilovepcs and got myself unbanned, take things serious ok? it makes you look dumb in front of **EVERYONE**

**Comment by iamshivayep** [comment]
then you call yourself "nOt UndErGe" not even a kid would do this nonsense

**Comment by iamshivayep** [comment]
just stop its not gonna take you anywhere

**Comment by KingTino104** [comment]
ok bai
