### ISSUE TITLE
Dark mode isn't working for control panel's side bar

### ISSUE THREAD

**Issue by verdaderoken** [MishaTY/Rectify11Installer#20]
Here's what it looks like 
![image](https://user-images.githubusercontent.com/88200096/185214879-b9eb7568-612b-4ce3-ba67-888b122824ff.png)

Currently using Rectify 11 v3
Windows 11 22H2 22622.575

**Comment by XPnerdYT** [comment]
Seems like shell32.dll.mun was not patched correctly, you'll have to reinstall or manually patch the file.

**Comment by verdaderoken** [comment]
> Seems like shell32.dll.mun was not patched correctly, you'll have to reinstall or manually patch the file.

It worked. Thank you
