### ISSUE TITLE
How to restore Windows 11 normal context menu?

### ISSUE THREAD

**Issue by EightStrings** [MishaTY/Rectify11Installer#26]
How to restore Windows 11 normal context menu?

**Comment by SmirbYrneh420** [comment]
[redesignedcontextmenus.zip](https://github.com/MishaTY/Rectify11Installer/files/9387819/redesignedcontextmenus.zip)
Run the EXE as admin and click uninstall.

**Comment by SmirbYrneh420** [comment]
And yes, I did extract this out of the old source code
