### ISSUE TITLE
Cant read text in control panel. explorar and maybe otherplaces if HDR is enabled

### ISSUE THREAD

**Issue by dudumaroja** [MishaTY/Rectify11Installer#29]
3.0 RP
Safe install 
Dark with mika
no enhanced ribbonui
no extended mica
no window 10 taskbat

I use a 4k as a monitor.. and if enable HDR i cant read  text in explorer and control panel and execute windows ( win+r) and probably a lot more.. i cant give some screenshots becouse for some reason in the screenshot the text apears ( probably beacouse screenshot wont support hdr )

**Comment by XPnerdYT** [comment]
Theres no fix for this, you'll just have to turn off HDR.

**Comment by MishaTY** [comment]
I think this is in normal windows 11.
