### ISSUE TITLE
'Turn Windows Features On And Off' wizard broken & BDEUnlock (and possibly other apps) blocked by Defender Application Control

### ISSUE THREAD

**Issue by Mnky313** [MishaTY/Rectify11Installer#3]
I know it's not released yet but I'd figure I would point out some stuff I've noticed. 

After running the installer and rebooting attempting to enable/disable anything from the 'Turn Windows Features On And Off' wizard (optionalfeatures) that requires a reboot will fail.

The system will reboot but it will say 'feature installation failed, reverting changes' and nothing will be applied.

Also when attempting to unlock a bitlocker protected drive you get a Metro style popup message that says 
'Your Organization Used Windows Defender Application Control To Block This App'
C:\Windows\System32\bdeunlock.exe

I assume this is because bdeunlock is patched because copying an unpatched one from a different install works fine.

AFAIK this isn't actually caused by defender in any way as I've completely removed it. (deleted files, stopped tasks from the registry, disabled it via GPO, etc.) with no change.

I've also tried disabling secure boot, integrity checks, and even testsigning mode with no change.

Thanks & Keep up the great work. :)

**Comment by dotxyzcf** [comment]
I can confirm this. and it sucks.

**Comment by MishaTY** [comment]
Fixed the issue with BDEUnlock (just had to comment it out in the XML file), and will fix the feature installation.

**Comment by Vichingo455** [comment]
Disable the UAC and all apps will work correctly

**Comment by FeyXieXzf** [comment]
> Disable the UAC and all apps will work correctly

I don't think everyone wants to dig a hole in the Windows' half-broken & nearly-useless security.
