### ISSUE TITLE
Reapply UxTheme patch when updating

### ISSUE THREAD

**Issue by Spaceox** [MishaTY/Rectify11Installer#33]
When using the update option in Rectify11, after a feature update, the installer won't reinstall UltraUXThemePatcher, making themes useless until the patch is installed.

Another option could be patching the necessary dlls in memory, like https://github.com/namazso/SecureUxTheme.
The latest release still works on Windows 11 and has the added benefit of persisting windows updates (although SystemSettings needs to be rehooked)

**Comment by XPnerdYT** [comment]
Thank you for your feedback, we will implement this if possible.
