### ISSUE TITLE
Windows 10 taskbar after restoration

### ISSUE THREAD

**Issue by Tobim6** [MishaTY/Rectify11Installer#34]
After restoring original windows 11 the taskbar is in windows 10 style and also I don't know if it should be like that but explorer patcher isn't removed after restoration

Fixed it by opening explorer patcher and setting the taskbar style to windows 11

Rectify11 v3.0-RP

**Comment by MishaTY** [comment]
You selected the windows 11 taskbar in the installer.

**Comment by Tobim6** [comment]
> You selected the windows 11 taskbar in the installer.

Yea and that's wrong?

**Comment by MishaTY** [comment]
I mean 10.

**Comment by Tobim6** [comment]
I selected windows 11
