### ISSUE TITLE
I have a question

### ISSUE THREAD

**Issue by foursplaysroblox** [MishaTY/Rectify11Installer#36]
is it safe to install Reactify 11 on an actual real computer?

**Comment by NukeThief** [comment]
yes i **had** rectify11 on my windows 11 21H2 newest release build and i forgot to even turn off my antivirus so resource hacker gave some errors but there is nothing more easy than pressing "enter" and it will continue and it worked like a charm definitely would recomend rectify11

**Comment by foursplaysroblox** [comment]
how about updating because im on the dev channel on my main computer

**Comment by foursplaysroblox** [comment]
and also where can i download the cursor in Rectify 11 by the way?

**Comment by RatchanonDev** [comment]
> and also where can i download the cursor in Rectify 11 by the way?

https://cdn.discordapp.com/attachments/972654792352616520/1000562133395849277/Cursors.zip
Rectify11 Cursors

To install and use:

1 Download the ZIP file
2 Extract the contents to a folder anywhere
3 Right click "Install", "Install Large", or "Install Extra Large", depending on your preference, then click "Install"
4 Open Settings > Personalization > Themes > Mouse cursor or type :Rectify11:+R > main.cpl
5 Go to the Pointers tab, select "Windows Rectified" from the dropdown menu, then click OK

This is from the Rectify11 discord.

**Comment by foursplaysroblox** [comment]
yea but the cursors look something like this
![image](https://user-images.githubusercontent.com/82078139/191243666-faa387ec-4156-4fa9-94b6-183153a71bcc.png)

**Comment by foursplaysroblox** [comment]
should*

**Comment by PeterNjeim** [comment]
> should*

In this thread you've demonstrated that you know how to edit both the titles of issues as well as editing comments themselves. Please do not edit your comments with new comments. Why? Because this isn't Discord, this is a subscription thread where people get emails whenever someone posts a message. Please use the edit function as it will edit "silently", instead of me getting an email that says "should*" lol. Hope you understand the difference between GitHub and other platforms

**Comment by NukeThief** [comment]
> how about updating because im on the dev channel on my main computer

Reinstall r11 or leave insider.

**Comment by hedhehd** [comment]
> > how about updating because im on the dev channel on my main computer
> 
> Reinstall r11 or leave insider.

Dude, how can he leave windows insider when you have to reinstall windows-

**Comment by XPnerdYT** [comment]
We do not really recommend you to install release preview versions, but in normal cases 3.0-RP2 should work fine. Please note that we do not take any responsibility of any damage to your device.
