### ISSUE TITLE
Is it safe to update Windows 11 with Rectify11 Installed?

### ISSUE THREAD

**Issue by NukeThief** [MishaTY/Rectify11Installer#37]
Idk i was kinda scared so i unistalled rectify11 before updating windows 11

**Comment by rounk-ctrl** [comment]
ok ig, but then you would need to apply again since windows update restores the files

**Comment by SnowzNZ** [comment]
oh my god. scared to update? iirc rectify11 only allows security updates so it should be fine

**Comment by nin0-dev** [comment]
it does not
22h2 updated successfully and broke r11

**Comment by XPnerdYT** [comment]
Rectify11 is completely ok with updates. Security updates and bug fixes are completely fine. For feature updates, you will have to reinstall Rectify11 but does not break any elements (except for R11, of course) of your Windows copy.
