### ISSUE TITLE
Uninstaller didn't uninstall nilesoft and accentcolorizer. 

### ISSUE THREAD

**Issue by fluentmoheshwar** [MishaTY/Rectify11Installer#39]
Uninstaller didn't uninstall nilesoft and accentcolorizer.  now help me uninstall it.

**Comment by Rex501st** [comment]
> Uninstaller didn't uninstall nilesoft and accentcolorizer. now help me uninstall it.

Also had this problem with nilesoft; install nilesoft from their official website, restart Windows explorer, go to control panel and uninstall nilesoft, and context menus should be normal now.

**Comment by fluentmoheshwar** [comment]
> > Uninstaller didn't uninstall nilesoft and accentcolorizer. now help me uninstall it.
> 
> Also had this problem with nilesoft; install nilesoft from their official website, restart Windows explorer, go to control panel and uninstall nilesoft, and context menus should be normal now.

I fixed it. But it should uninstall everything. uninstalling accentcolorizer was a pain. But I managed to uninstall it.

**Comment by Rex501st** [comment]
> > > Uninstaller didn't uninstall nilesoft and accentcolorizer. now help me uninstall it.
> > 
> > 
> > Also had this problem with nilesoft; install nilesoft from their official website, restart Windows explorer, go to control panel and uninstall nilesoft, and context menus should be normal now.
> 
> I fixed it. But it should uninstall everything. uninstalling accentcolorizer was a pain. But I managed to uninstall it.

I agree.

**Comment by XPnerdYT** [comment]
Probably an issue with the codebass of older versions, once again.
