### ISSUE TITLE
System.ComponentModel.Win32Exception

### ISSUE THREAD

**Issue by donut2008** [MishaTY/Rectify11Installer#4]
![image](https://user-images.githubusercontent.com/76439683/181497728-48a0bf56-0adb-44e4-bdae-c9bd0e4c9889.png)
Each time I go past the EULA I get this error. The installer is running as admin.
WIndows 11 build 22000.832

**Comment by rounk-ctrl** [comment]
Fixed

**Comment by donut2008** [comment]
![image](https://user-images.githubusercontent.com/76439683/182014103-698c8f5f-98a3-40b1-bd44-b10395611d2b.png)
Well now I get this, downloaded latest release

**Comment by rounk-ctrl** [comment]
Should be fixed

**Comment by rounk-ctrl** [comment]
Actually idk how to fix this.

**Comment by rounk-ctrl** [comment]
bruh

**Comment by donut2008** [comment]
As of v3.0 RP the installer works normally, no crashes or anything
