### ISSUE TITLE
SecureUxTheme insted of UXthemepatcher

### ISSUE THREAD

**Issue by Caticer** [MishaTY/Rectify11Installer#41]
I dont know if its possible or not but I think [SecureUxTheme](https://github.com/namazso/SecureUxTheme) better than Uxthemepatcher.

SecureUxTheme  Features:
* No system file modifications
* No driver needed
* Secure boot compatible
* Probably quite future-proof
* Fixes LogonUI resetting some colors on locking

**Comment by rounk-ctrl** [comment]
yeah it will be a choice in final installer
