### ISSUE TITLE
PC Bootlooping at Stage 1,

### ISSUE THREAD

**Issue by spIoopy** [MishaTY/Rectify11Installer#42]
Alright, so heres the thing, I chose to install recitfy11 by using this, After it told me to restart after booting up, my boot logo faded in, and then restarted, Ive tried going into safe mode but i only got to boot into safe mode for 1 second, I tried to uninstall Rectify11 using hiren bootcd, but the uninstall option was greyed out, My SSD Is still safe and no data was erased, Please help!

**Comment by rounk-ctrl** [comment]
boot your computer using a windows installation medium, open command prompt(shift+f10) open regedit, click on HKEY_LOCAL_MACHINE, click file in the menu and select Load hive. Then navigate to [drive where you have windows 11 installation]:\windows\system32\config, select the SYSTEM file, put any random name then click ok. Then expand the randomly named key and select Setup. On the right side, make evey REG_DWORD 0, make CmdLine blank then reboot. It should hopefully fix.

**Comment by spIoopy** [comment]
> boot your computer using a windows installation medium, open command prompt(shift+f10) open regedit, click on HKEY_LOCAL_MACHINE, click file in the menu and select Load hive. Then navigate to [drive where you have windows 11 installation]:\windows\system32\config, select the SYSTEM file, put any random name then click ok. Then expand the randomly named key and select Setup. On the right side, make evey REG_DWORD 0, make CmdLine blank then reboot. It should hopefully fix.

holy sh*t god bless you, what could i do without you, my computer finally works again
