### ISSUE TITLE
Xbox Game Bar completely broken

### ISSUE THREAD

**Issue by GabrielStuffs** [MishaTY/Rectify11Installer#45]
When opening the Xbox Game Bar, the screen goes completely grey (except for the Game Bar elements) and I have to restart my PC. Hope this is patched in an update.

**Comment by RatchanonDev** [comment]
It go completely grey for me too but when I click on the grey space it exit gamebar and go back to normal desktop.
![image](https://user-images.githubusercontent.com/65711396/189474048-0d8af622-d873-4ad0-b74f-588263230adc.png)

**Comment by HackerDaGreat57** [comment]
For me it works. Just saying it doesn't happen to everyone.

**Comment by Hema2-official** [comment]
I have this issue with Overwolf after installing Rectify11...

**Comment by lvlvlvboliqiu** [comment]
I remember that I have seen the same problem in the issue of "micaforeveryone"

**Comment by XPnerdYT** [comment]
Add a process rule by the name of the process 
![image](https://user-images.githubusercontent.com/87585714/207999793-c31d716f-efd6-45f1-9366-3a5d396cd155.png)
![image](https://user-images.githubusercontent.com/87585714/207999820-56375b97-91ea-4fb2-8214-41b0c1da5e7a.png)

**Comment by XPnerdYT** [comment]
Please note that the settings should be something like this
![image](https://user-images.githubusercontent.com/87585714/208000071-7d040862-512b-4b68-acbb-5e034ca3d948.png)
