### ISSUE TITLE
Unable to change start menu Recommendation section options.

### ISSUE THREAD

**Issue by haminnhtri5555** [MishaTY/Rectify11Installer#49]
After rectified my Windows 11 Dev Insiders, I cannot change the Recommendation section on the Start menu, I won't go down or move up.

**Comment by Yoad1704** [comment]
I might not be an expert but to help you I need an answer:
What is the version of your build in the dev channel? Can you actually install Rectify11 while in the dev channel without problems - or did you do some modifications to make it work that might be causing the issue?
AGAIN, IM NOT AN EXPERT I LEARNED ALL FROM TRYING

**Comment by nin0-dev** [comment]
Re-patch system

**Comment by XPnerdYT** [comment]
Try checking the ExplorerPatcher settings.
