### ISSUE TITLE
Starting with version 2.9.6.5, the icons won’t install at all

### ISSUE THREAD

**Issue by SmirbYrneh420** [MishaTY/Rectify11Installer#5]
The installers with a single .exe file do not install any icons. Stage 2 of the setup installs extremely quickly (installs themes only), which is a medium red flag. Pretty self-explanatory.

**Comment by SmirbYrneh420** [comment]
Tried everything to work around this, including running the installer in a VM.
And yes, before you ask, I did turn off real-time protection and even used Winaero Tweaker to disable Defender.
Either way, Stage 2 of the setup skips from WinRE straight to optional features, only installing everything BUT the icons

**Comment by XPnerdYT** [comment]
We're sorry to hear about that. This should (hopefully) be fixed on the final release as our old source code was shit and pretty much depends fully on luck. This was also the reason why we delayed the final release as we are working on a new codebase.
