### ISSUE TITLE
Add StartAllBack (Activated)

### ISSUE THREAD

**Issue by BlueYo4567** [MishaTY/Rectify11Installer#52]
Add StartAllBack for Mica header bar in Control Panel
**Like this:**
![image](https://user-images.githubusercontent.com/96501474/197356021-6ae46702-0fcd-498b-81c7-20a7f77c1ac6.png)

**With these settings in Explorer menu**
![image](https://user-images.githubusercontent.com/96501474/197356259-ee8df260-1f7f-46fd-acb6-d7b45844b408.png)

**And the start menu and taskbar disabled for Windows 11 system start menu and taskbar**

**Comment by MishaTY** [comment]
We will not add StartAllBack, as it's closed source and paid. We also will **not** include cracked software.
