### ISSUE TITLE
Is the "fix automatic restart" related to this thing where my PC kept rebooting a lot?

### ISSUE THREAD

**Issue by mx4address** [MishaTY/Rectify11Installer#56]
Hello.

I noticed that in the latest version of Rectify11 it fixed "automatic restart issues", is it relating to the system keeping on rebooting..?
Because one time I installed it and left my PC off for a while, when I powered it back on it kept restarting over and over..
Thinking it was likely a virus or something, I am just asking if it's Rectify11, or me.

**Comment by MishaTY** [comment]
yes
