### ISSUE TITLE
if the files or folders already exists, installer stops working and only few were successfully patched (ex: when reinstalling)

### ISSUE THREAD

**Issue by MuscularPuky** [MishaTY/Rectify11Installer#57]
![2022-11-10](https://user-images.githubusercontent.com/93962018/201030843-ce1264bf-ea6c-49c9-8fda-eb9232e5350d.png)
![20221110_165331](https://user-images.githubusercontent.com/93962018/201033448-480b23a5-24bf-47d0-b0cd-d308fa2c1915.jpg)

the result is similar to this: https://github.com/MishaTY/Rectify11Installer/issues/48

and even uninstaller does nothing. modern context menu is completly gone, nliesoft shell is not removed, and other components are too.(maybe modern search too) cannot revert rectify11, execpt for icons.

the solutions are:
1. overwrite or skip. i think that's simple.
2. or delete the components completly when uninstalling. but this solution won't work if user accidentally has files or folders with the same name.
3. installer won't end even though the file copying is partially successed. need exception handling for this.

**Comment by xAvatar6969** [comment]
yeah I have this issue too, I don't know how to proceed

**Comment by XPnerdYT** [comment]
This was an issue caused by our codebase. It has been completely revamped and should not happen again.
