### ISSUE TITLE
Error when installing Full version

### ISSUE THREAD

**Issue by JoshyJoshyJoshy** [MishaTY/Rectify11Installer#58]
![image](https://user-images.githubusercontent.com/83929921/202932933-f3024571-3a37-43c5-bcf4-9d176902c062.png)

**Comment by TomCena** [comment]
got the same issue

**Comment by Pusheon** [comment]
just remove the menu, for some reason it doesnt remove the dir when uninstalling

**Comment by xAvatar6969** [comment]
same issue

**Comment by JoshyJoshyJoshy** [comment]
I cannot remove the menu, my actual computer doesn't let me

**Comment by XPnerdYT** [comment]
This issue should be fixed in the new version. Install 3.0-RP2.

**Comment by xAvatar6969** [comment]
> This issue should be fixed in the new version. Install 3.0-RP2.

yeah, but how to I fix the fact that the system apps are half black and half white, it's impossible to read text
