### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by boromyr** [MishaTY/Rectify11Installer#59]
I've tried compiling Rectify11 to try out the latest updates, but I'm getting the error:
`2>D:\Rectify11Installer\Rectify11Installer\Properties\Resources.resx(6618,5): error MSB3103: Invalid Resx file. The file 'D:\Rectify11Installer\Rectify11Installer\Resources\files.7z' It was not found. Row 6618, position 5.`
The files.7z file is not present in this repository, would it be possible to upload it?

**Comment by rounk-ctrl** [comment]
later when v3 releases

**Comment by rounk-ctrl** [comment]
if you want the 7z, dm me in discord

**Comment by boromyr** [comment]
ok, can you leave a link to contact you?

**Comment by rounk-ctrl** [comment]
> ok, can you leave a link to contact you?
you dont have discord? fine here you go, https://gofile.io/d/Dr4EAk

**Comment by boromyr** [comment]
it works thanks a lot
