### ISSUE TITLE
Starting with v. 2.9.6.5, none of the icons install (not even shell32 or imageres)

### ISSUE THREAD

**Issue by SmirbYrneh420** [MishaTY/Rectify11Installer#6]
The installers with a single .exe file do not install any icons. Stage 2 of the setup installs extremely quickly (installs themes only), which is a medium red flag. Pretty self-explanatory.

**Comment by rounk-ctrl** [comment]
Try deleting the rectify11 folder located in C:\Windows

**Comment by SmirbYrneh420** [comment]
I tried moving it to an external drive, unplugging it, then rebooting. Didn't work.

**Comment by SmirbYrneh420** [comment]
Windows 11 build 22621.440, beta channel

**Comment by SmirbYrneh420** [comment]
Deleting it didn’t work either

**Comment by MishaTY** [comment]
Fixed

**Comment by SmirbYrneh420** [comment]
Persists in release preview

**Comment by MishaTY** [comment]
Can you send the log file in System32?

**Comment by SmirbYrneh420** [comment]
What is the log file name?

**Comment by SmirbYrneh420** [comment]
[installer.log](https://github.com/MishaTY/Rectify11Installer/files/9276788/installer.log)
It seems that the installer doesn't see the resources it needs, therefore skipping them.
What's weird is that Windows Defender did not brick my device and the installer did not give any errors I could see.

**Comment by SmirbYrneh420** [comment]
I once tried using winaero tweaker to disable it and it produces same result

**Comment by SmirbYrneh420** [comment]
Tried disabling real-time protection and installing in a VMware VM. It produced the same effect.
