### ISSUE TITLE
Better way to compose Context menu

### ISSUE THREAD

**Issue by x-0D** [MishaTY/Rectify11Installer#60]
![image](https://user-images.githubusercontent.com/87000516/207041568-a6edb6c6-9856-4b37-ada6-24b540aae9ea.png)
How can I edit/modify context menu for my needs? (With disabled win11 context menu)

**Comment by x-0D** [comment]
I looked at overloaded context menu on my friend's computer and i think this variant much better than original.
Here some constructive critics at this context menu variant
![Снимок экрана_20221212_150914](https://user-images.githubusercontent.com/87000516/207046780-4995cc28-ee38-4367-a6a6-deb28c959cf6.png)

Want to help Rectify 11 project to be really windows fixer not a troublemaker

**Comment by x-0D** [comment]
https://github.com/moudey/shell
Some interesting context menu project

**Comment by XPnerdYT** [comment]
> https://github.com/moudey/shell
> Some interesting context menu project
Isn't that just nilesoft shell though

**Comment by MishaTY** [comment]
We have already tried using it.
