### ISSUE TITLE
Few issues in the RP 2

### ISSUE THREAD

**Issue by Vichingo455** [MishaTY/Rectify11Installer#65]
1. The form looks a bit broken:
![image](https://user-images.githubusercontent.com/59311016/208149146-24c38e78-6012-4495-9563-cd1b01b39de0.png)
![image](https://user-images.githubusercontent.com/59311016/208149188-b30d762f-fb89-4249-8241-58574201dcb6.png)
2. Trying to cancel the installation after the first screen will show 2 confirmation prompts for close
3. Italian translations a bit incomplete
4. Idk why but I can't use Visual Studio 2022 to edit it
![image](https://user-images.githubusercontent.com/59311016/208149660-c4c62740-16e6-4d4c-9527-d05d63ab101e.png)

**Comment by rounk-ctrl** [comment]
1. ok dpi issue
2. ok
3. u made pr
4. yes it doesnt work with winforms editor

**Comment by rounk-ctrl** [comment]
what do you mean 2 confirmation prompts i only see 1

**Comment by Vichingo455** [comment]
> 1. ok dpi issue
> 2. ok
> 3. u made pr
> 4. yes it doesnt work with winforms editor

How can I edit it without WinForms editor?

**Comment by rounk-ctrl** [comment]
open the designer.cs file

**Comment by A-Loot** [comment]
> what do you mean 2 confirmation prompts i only see 1

@rounk-ctrl The 2 exit prompts appear on every page except the first one

https://user-images.githubusercontent.com/105282948/212280336-207a2665-b170-442e-ac33-2fb781524fcb.mp4

**Comment by rounk-ctrl** [comment]
Oh
