### ISSUE TITLE
Inactive explorer window turns black

### ISSUE THREAD

**Issue by x-0D** [MishaTY/Rectify11Installer#67]
Windows 11 Build 25267.rs_prerelease.221209-1557

![image](https://user-images.githubusercontent.com/87000516/208163704-5df6c3b0-ecd7-41d1-8782-7e031d4f94cb.png)
Inactive explorer window turns black

![image](https://user-images.githubusercontent.com/87000516/208164349-6e3781bc-e320-423f-8866-0b0707a56342.png)
explorer windows saves it's colors when at least one explorer window keeps active

![image](https://user-images.githubusercontent.com/87000516/208164024-ab433521-6545-4e27-aeee-2c40e4f4fbf1.png)
Inactive explorer window saves normal color, but last inactive window turns black

Updating Mica For Everyone in C:\Windows folder to newer (1.2.0.1) version doesn't help

**Comment by XPnerdYT** [comment]
This is a known issue on the side of MFE (MicaForEveryone), and due to limitations of windows, and other things, they cannot seem to fix it soon. Currently, the only solution would be to use this executable (it seems to falsely trigger Windows Defender, so disable it before downloading) https://cdn.discordapp.com/attachments/973623343800537128/994259101125185536/AlwayMicaforEx.exe
![image](https://user-images.githubusercontent.com/87585714/208216506-109d27cb-86d6-4059-a937-6aa2984a8ace.png)

**Comment by dongle-the-gadget** [comment]
Does [ExplorerFrame](https://github.com/MicaForEveryone/ExplorerFrame) help?

**Comment by x-0D** [comment]
@XPnerdYT This executable don't help.

**Comment by XPnerdYT** [comment]
> Does [ExplorerFrame](https://github.com/MicaForEveryone/ExplorerFrame) help?

Try that, it seems to work for me.

**Comment by x-0D** [comment]
@XPnerdYT can you provide Explorerframe executable for me?

**Comment by dongle-the-gadget** [comment]
> @XPnerdYT can you provide Explorerframe executable for me? Telegram: appleroot.t.me Discord: Hex0S#4767

They are in Releases.

**Comment by x-0D** [comment]
@XPnerdYT works for me too. (Except that i should use vpn sometimes to properly load github commits and release pages)

**Comment by x-0D** [comment]
@dongle-the-gadget can you delete my contact information from comment?

**Comment by dongle-the-gadget** [comment]
No - I don't have permission on this repo.

**Comment by SylveonBottle** [comment]
Unsure if this is related, but I'm having a similar issue when attempting to resize an explorer window.

https://user-images.githubusercontent.com/17802843/230694123-f577bd89-9f4f-4991-b1a9-d3e7b65d5dfc.mp4
