### ISSUE TITLE
Cant uninstall

### ISSUE THREAD

**Issue by Radical4ever** [MishaTY/Rectify11Installer#71]
-hi, apart from the fact that the theming doesn't  worked (but applying icons in control panel yes), the uninstaller wont let me press the uninstall button it figures as a new install

**Comment by SylveonDeko** [comment]
it literally says themes doesnt work right now

**Comment by Radical4ever** [comment]
> it literally says themes doesnt work right now

woops, forget to read that!

**Comment by rounk-ctrl** [comment]
Will be implemented

**Comment by IWSM** [comment]
**Please, solution for Uninstall** Probleme on explorer font black and more
<img width="887" alt="Capture d’écran 2023-01-05 112121" src="https://user-images.githubusercontent.com/63722574/210757550-4f54f304-803f-4666-aaf2-b0d5c12500d8.png">

**Comment by rounk-ctrl** [comment]
Tracked in #99

**Comment by PwrSrg** [comment]
I am also unable to uninstall using RP3.  Clicking the uninstall button does **NOTHING**.

**Comment by MishaTY** [comment]
Tracked in #99

**Comment by Snasdagamer** [comment]
yeah i cant uninstall it. at least give it a good font
![Screenshot 2023-05-31 073024](https://github.com/MishaProductions/Rectify11Installer/assets/135141158/be26c2e0-5318-4146-a822-0b5a15c0660e)
![Screenshot 2023-05-31 073220](https://github.com/MishaProductions/Rectify11Installer/assets/135141158/54f8d225-2451-47b7-996f-5d25d70fba68)

**Comment by badalsharmaa** [comment]
same condition here
