### ISSUE TITLE
NET Issue

### ISSUE THREAD

**Issue by Windows3280** [MishaTY/Rectify11Installer#88]
### Description

I have installed a .NET desktop runtime 6.0.7 distributed in assets for 3.0-RP, it says i haven't got the runtime. Pls help!

### Steps To Reproduce

i am installing net and running r11 setup, it says no .net runtime :(

### Rectify11 Version

3.0-RP

### Windows Version

windows 11 build 25193.1001

### Logs

You haven't got NET runtime. Please install it. (but i have it installed)

**Comment by Typical0** [comment]
Please use newer versions (v3.0 RP2 and newer). v3.0-RP is known for it's instability.
