### ISSUE TITLE
Uninstall issues

### ISSUE THREAD

**Issue by alexxa4** [MishaTY/Rectify11Installer#89]
### Description

Pressing uninstall results in the installer doing nothing.

### Steps To Reproduce

Install Rectify11
Attempt to uninstall Rectify11

### Rectify11 Version

3.0

### Windows Version

Windows 11 Version 22H2 Build 22621.525

### Logs

No logs and no way to send a video of the issue

**Comment by SmirbYrneh420** [comment]
known issue, dev said will implement in next release preview or whatever

**Comment by SmirbYrneh420** [comment]
https://github.com/MishaTY/Rectify11Installer/issues/71#issuecomment-1356722867

**Comment by ProCode-Software** [comment]
How do we uninstall it now?
